Flash attention for rocm
ROCm/flash-attention pull request #1
Opened 2023-02-17 22:57 UTC by groenenboomj

Add ROCm support for forward pass kernels.

2023-02-17 23:06 UTC, amathews-amd requested changes
Merging blocked till process identified

2023-04-21 02:41 UTC, sunway513 approved these changes

2023-04-21 13:06 UTC, amathews-amd approved these changes
LGTM

2024-01-31 05:11 UTC, ehartford commented
What's this for?  should I use this branch?

2025-01-29 17:26 UTC, micmelesse commented
Closing this pr. We have upstreamed support for the ck backend and in the process of upstreaming the Triton backend.

2025-01-29 17:26 UTC, closed without merging